name = "shamji-web"
compatibility_date = "2025-09-28"

# Static site configuration for Cloudflare Pages
[assets]
directory = "./dist"

# Optional: Custom domain configuration
# [env.production]
# routes = [
#   { pattern = "shamji-ads.com", zone_name = "shamji-ads.com" },
#   { pattern = "www.shamji-ads.com", zone_name = "shamji-ads.com" }
# ]
