name = "shamji-web"
compatibility_date = "2025-09-28"

[assets]
directory = "./dist"
binding = "ASSETS"

# Optional: Custom domain configuration
# [env.production]
# routes = [
#   { pattern = "shamji-ads.com", zone_name = "shamji-ads.com" },
#   { pattern = "www.shamji-ads.com", zone_name = "shamji-ads.com" }
# ]

# Build configuration for Cloudflare Pages
[build]
command = "bun run build"
cwd = "."
watch_dir = "src"
